### ISSUE TITLE
What features are implemented currently?

### ISSUE THREAD

**Issue by bdrelling** [Clusterize/Xamarin-Braintree.iOS-Bindings#1]
We're looking to use your binding of the Braintree SDK. Rather than duplicate the work, I was hoping to use what you've bound and shared, but the README.md file says that, "a limited set of functionality is implemented," but didn't give specifics as to what was / wasn't included.

**Comment by nirinchev** [comment]
Hi, sorry for the vague description in the readme. If you look at https://github.com/Clusterize/Xamarin-Braintree.iOS-Bindings/blob/master/BraintreeBindings/ApiDefinition.cs, you can see exactly which methods are bound. Generally, I've bound everything I needed to get the Drop-In UI to work, including most of the customization options.

Basically, you can use it like:
```
var controller = Braintree.Create("*your_token*").CreateDropInController(MyDelegate);
controller.FetchPaymentMethods();
controller.SummaryTitle = "2 packs of dog food";
controller.SummaryDescription = "Your dog will love it!";
controller.DisplayAmount = "$45";
controller.CallToActionText = "Buy now!";
this.PresentViewController(controller);
```

where ```MyDelegate``` is a class that implements ```BTDropInViewControllerDelegate```.

Additionally, I've bound ```TokenizeCard``` and theoretically, it should work, but haven't used it in production, since the Drop-In UI takes care of that internally.

If you do need other methods and bind them, I'd be happy to get a PR :)
